  name: CI
  on:
    push: 
      branches:  [master]

      workflow_dispatch:

jobs: 
  build:
    run-on: ubuntu-latest

      steps: 
        -  uses: actions/checkout@v2
        - name: run one line script
          run: echo Helo, Word!   

      
  
